openapi: 3.0.3
info:
  title: INOA API - ThingType
  description: API for defining thing types
  version: ${project.version}
  license:
    name: Apache License 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: inoa.io
    url: https://github.com/inoa-io
servers: []
paths: {}
