name: CI

on:
  push:
    branches: [main]
    tags-ignore: "**"
  pull_request: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
        with:
          args: /github/workspace

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-id: github.com
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp verify
        if: ${{ github.ref != 'refs/heads/main' }}
      - run: mvn -B -ntp deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
